const MOVIE_CONTEXT = '@store/movie';

const FETCH_MOVIES = `${MOVIE_CONTEXT}/FETCH_MOVIES`;
const FETCH_MOVIES_SUCCESS = `${MOVIE_CONTEXT}/FETCH_MOVIES_SUCCESS`;
const FETCH_MOVIES_FAILED = `${MOVIE_CONTEXT}/FETCH_MOVIES_FAILED`;
const CLEAR_LIST = `${MOVIE_CONTEXT}/CLEAR_LIST`;

export { FETCH_MOVIES, FETCH_MOVIES_SUCCESS, FETCH_MOVIES_FAILED, CLEAR_LIST };
