const MOVIE_CONTEXT = '@store/details';

const FETCH_DETAILS = `${MOVIE_CONTEXT}/FETCH_DETAILS`;
const FETCH_DETAILS_SUCCESS = `${MOVIE_CONTEXT}/FETCH_DETAILS_SUCCESS`;
const FETCH_DETAILS_FAILED = `${MOVIE_CONTEXT}/FETCH_DETAILS_FAILED`;

export { FETCH_DETAILS, FETCH_DETAILS_SUCCESS, FETCH_DETAILS_FAILED };
